# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rake/testtask'
require 'rubocop/rake_task'
require 'yard'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.test_files = FileList['test/**/*_test.rb']
end

RuboCop::RakeTask.new

YARD::Rake::YardocTask.new(:doc) do |t|
  t.files = [ 'lib/**/*.rb' ]
  t.options = [ '--output-dir', 'doc' ]
end

desc 'Start an interactive console with the SDK loaded'
task :console do
  exec 'bin/console'
end

task default: %i[test rubocop]
